package com.henry.signapp;

import android.content.Intent;
import android.os.Bundle;

import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;

public class Login extends AppCompatActivity {
    public final static String EMAIL = "com.henry.signapp.EMAIL";
    private EditText emailText, passwordText;
    private Button newUser, login;
    private String email, password;
    private FirebaseAuth auth;
    private FirebaseHelper db = FirebaseHelper.getInstance();
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        //Get authentication instance
        auth = FirebaseAuth.getInstance();

        //If there is a User logged in, redirect to homepage
        if(auth.getCurrentUser() != null){
            startActivity(new Intent(Login.this, Homepage.class));
            finish();
        }

        String[][] categories = new String[][]{{"Time"	,	"time"	},
                {	"Shapes"	,	"shapes"	},
                {	"Places"	,	"places"	},
                {	"Numbers"	,	"numbers"	},
                {	"Leisure Activities"	,	"Leisure Activites"	},
                {	"Family & People"	,	"Family & People"	},
                {	"Commands"	,	"commands"	},
                {	"Animals"	,	"animals"	}

        };
        for(int i=0; i<categories.length; i++){
            db.addCategory(categories[i][0]);
        }

        String[][] gifs = new String[][]{{	"Animals","animal","Animal","0","0"	},
        {	"Animals","bat-flying","Bat (Flying)","0","0"	},
        {	"Animals","bat-vampire","Bat (Vampire)","0","0"	},
        {	"Animals","bear","Bear","0","0"	},
        {	"Animals","bee","Bee","0","0"	},
        {	"Animals","cat","Cat","0","0"	},
        {	"Animals","catb","Cat","0","0"	},
        {	"Animals","cow","Cow","0","0"	},
        {	"Animals","dinosaur","Dinosaur","0","0"	},
        {	"Animals","dog-d-o-g","Dog","0","0"	},
        {	"Animals","doga","Dog","0","0"	},
        {	"Animals","dogb","Dog","0","0"	},
        {	"Animals","donkey","Donkey","0","0"	},
        {	"Animals","eagle","Eagle","0","0"	},
        {	"Animals","elephant","Elephant","0","0"	},
        {	"Animals","elephantversion2","Elephant","0","0"	},
        {	"Animals","fish","Fish","0","0"	},
        {	"Animals","pet","Pet","0","0"	},
        {	"Commands","accept","Accept","0","0"	},
        {	"Commands","become","Become","0","0"	},
        {	"Commands","begin","Begin","0","0"	},
        {	"Commands","calm-down","Calm Down","0","0"	},
        {	"Commands","careful","Careful","0","0"	},
        {	"Commands","chase","Chase","0","0"	},
        {	"Commands","chase2","Chase","0","0"	},
        {	"Commands","cheat","Cheat","0","0"	},
        {	"Commands","climb","Climb","0","0"	},
        {	"Commands","collect","Collect","0","0"	},
        {	"Commands","connect","Connect","0","0"	},
        {	"Commands","contact","Contact","0","0"	},
        {	"Commands","destroy","Destroy","0","0"	},
        {	"Commands","dig","Dig","0","0"	},
        {	"Commands","dig2","Dig","0","0"	},
        {	"Commands","discuss","Discuss","0","0"	},
        {	"Commands","enter","Enter","0","0"	},
        {	"Commands","excuse","Excuse","0","0"	},
        {	"Commands","explain","Explain","0","0"	},
        {	"Commands","fail","Fail","0","0"	},
        {	"Commands","failb","Fail","0","0"	},
        {	"Commands","failc","Fail","0","0"	},
        {	"Commands","faild","Fail","0","0"	},
        {	"Commands","fallbehind","Fall Behind","0","0"	},
        {	"Commands","fall-down","Fall Down","0","0"	},
        {	"Commands","fallinlove","Fall In Love","0","0"	},
        {	"Commands","feed","Feed","0","0"	},
        {	"Commands","find","Find","0","0"	},
        {	"Commands","follow","Follow","0","0"	},
        {	"Commands","force","Force","0","0"	},
        {	"Commands","forgeta","Forget","0","0"	},
        {	"Commands","forgetb","Forget","0","0"	},
        {	"Commands","get","Get","0","0"	},
        {	"Commands","stand-getup","Get Up","0","0"	},
        {	"Commands","give-givetoeverybody","Give To Everybody","0","0"	},
        {	"Commands","give-himgivetome","Give To Me","0","0"	},
        {	"Commands","give-up","Give Up","0","0"	},
        {	"Commands","gomakeyourbed","Go Make Your Bed","0","0"	},
        {	"Commands","give-handtoeachone","Hand To Each One","0","0"	},
        {	"Commands","hit","Hit","0","0"	},
        {	"Commands","increase","Increase","0","0"	},
        {	"Commands","laugh","Laugh","0","0"	},
        {	"Commands","laydown","Laydown","0","0"	},
        {	"Commands","listen","Listen","0","0"	},
        {	"Commands","lookat-that","Look At That","0","0"	},
        {	"Commands","lookat","Lookat","0","0"	},
        {	"Commands","loud","Loud","0","0"	},
        {	"Commands","make","Make","0","0"	},
        {	"Commands","bedmake","Make The Bed","0","0"	},
        {	"Commands","give-megivehim","Me Give To Him","0","0"	},
        {	"Commands","give-megiveyou","Me Give To You","0","0"	},
        {	"Commands","move","Move","0","0"	},
        {	"Commands","no","No","0","0"	},
        {	"Commands","not","Not","0","0"	},
        {	"Commands","put-pack","Pack","0","0"	},
        {	"Commands","play","Play","0","0"	},
        {	"Commands","put","Put","0","0"	},
        {	"Commands","put-away","Put Away","0","0"	},
        {	"Commands","shutup","Shutup","0","0"	},
        {	"Commands","sit","Sit","0","0"	},
        {	"Commands","put-sortout","Sort Out","0","0"	},
        {	"Commands","speak","Speak","0","0"	},
        {	"Commands","spread","Spread","0","0"	},
        {	"Commands","stand-up","Stand Up","0","0"	},
        {	"Commands","call-summon","Summon","0","0"	},
        {	"Commands","talk","Talk","0","0"	},
        {	"Commands","tell","Tell","0","0"	},
        {	"Commands","tell-him","Tell Him","0","0"	},
        {	"Commands","tell-me","Tell Me","0","0"	},
        {	"Commands","throw","Throw","0","0"	},
        {	"Commands","put-inslot","To Put In A Slot","0","0"	},
        {	"Commands","trade","Trade","0","0"	},
        {	"Commands","turn","Turn","0","0"	},
        {	"Commands","visit","Visit","0","0"	},
        {	"Commands","wake-up","Wake Up","0","0"	},
        {	"Commands","walk","Walk","0","0"	},
        {	"Commands","walkto","Walk To","0","0"	},
        {	"Commands","yell","Yell","0","0"	},
        {	"Commands","give-yougiveme","You Give To Me","0","0"	},
        {	"Family & People","accountantag","Accountant","0","0"	},
        {	"Family & People","actor","Actor","0","0"	},
        {	"Family & People","american","American","0","0"	},
        {	"Family & People","americanindian","American Indian","0","0"	},
        {	"Family & People","artist","Artist","0","0"	},
        {	"Family & People","boss","Boss","0","0"	},
        {	"Family & People","bother","Bother","0","0"	},
        {	"Family & People","inlawbrother","Brother Inlaw","0","0"	},
        {	"Family & People","inlawbrotherb","Brother Inlaw","0","0"	},
        {	"Family & People","carpenter","Carpenter","0","0"	},
        {	"Family & People","child","Child","0","0"	},
        {	"Family & People","children","Children","0","0"	},
        {	"Family & People","childrentwohanded","Children (Two Handed)","0","0"	},
        {	"Family & People","chineseold","Chinese","0","0"	},
        {	"Family & People","daughter","Daughter","0","0"	},
        {	"Family & People","daughterb","Daughter","0","0"	},
        {	"Family & People","doctor","Doctor","0","0"	},
        {	"Family & People","farmer","Farmer","0","0"	},
        {	"Family & People","fireman","Fireman","0","0"	},
        {	"Family & People","firemanb","Fireman","0","0"	},
        {	"Family & People","himself","Himself","0","0"	},
        {	"Family & People","inlaw","Inlaw","0","0"	},
        {	"Family & People","girl-littlegirl","Little Girl","0","0"	},
        {	"Family & People","magician","Magician","0","0"	},
        {	"Family & People","manversiona","Man","0","0"	},
        {	"Family & People","manversionb","Man","0","0"	},
        {	"Family & People","manversionc","Man","0","0"	},
        {	"Family & People","myself","Myself","0","0"	},
        {	"Family & People","neighbor","Neighbor","0","0"	},
        {	"Family & People","neighborb","Neighbor","0","0"	},
        {	"Family & People","people","People","0","0"	},
        {	"Family & People","police","Police","0","0"	},
        {	"Family & People","policeb","Police","0","0"	},
        {	"Family & People","president","President","0","0"	},
        {	"Family & People","scientist","Scientist","0","0"	},
        {	"Family & People","scientistb","Scientist","0","0"	},
        {	"Family & People","secretary","Secretary","0","0"	},
        {	"Family & People","secretarya","Secretary","0","0"	},
        {	"Family & People","secretaryc","Secretary","0","0"	},
        {	"Family & People","singer","Singer","0","0"	},
        {	"Family & People","singer2","Singer","0","0"	},
        {	"Family & People","inlawsister","Sister Inlaw","0","0"	},
        {	"Family & People","son","Son","0","0"	},
        {	"Family & People","sonb","Son","0","0"	},
        {	"Family & People","sophomore","Sophomore","0","0"	},
        {	"Family & People","brother-step","Step Brother","0","0"	},
        {	"Family & People","dad-step","Step Dad","0","0"	},
        {	"Family & People","father-step","Step Father","0","0"	},
        {	"Family & People","mother-step","Step Mother","0","0"	},
        {	"Family & People","sister-step","Step Sister","0","0"	},
        {	"Family & People","waitress","Waitress","0","0"	},
        {	"Leisure Activities","bake","Bake","0","0"	},
        {	"Leisure Activities","ball","Ball","0","0"	},
        {	"Leisure Activities","baseball","Baseball","0","0"	},
        {	"Leisure Activities","basketball","Basketball","0","0"	},
        {	"Leisure Activities","bat","Bat","0","0"	},
        {	"Leisure Activities","book","Book","0","0"	},
        {	"Leisure Activities","camera","Camera","0","0"	},
        {	"Leisure Activities","computer","Computer","0","0"	},
        {	"Leisure Activities","cook","Cook","0","0"	},
        {	"Leisure Activities","fishing","Fishing","0","0"	},
        {	"Leisure Activities","hike","Hike","0","0"	},
        {	"Leisure Activities","hockey","Hockey","0","0"	},
        {	"Leisure Activities","internet","Internet","0","0"	},
        {	"Leisure Activities","internetb","Internet","0","0"	},
        {	"Leisure Activities","movie","Movie","0","0"	},
        {	"Leisure Activities","music","Music","0","0"	},
        {	"Leisure Activities","poetry","Poetry","0","0"	},
        {	"Leisure Activities","race","Race","0","0"	},
        {	"Leisure Activities","read","Read","0","0"	},
        {	"Leisure Activities","rollerblade","Rollerblade","0","0"	},
        {	"Leisure Activities","run","Run","0","0"	},
        {	"Leisure Activities","run2","Run","0","0"	},
        {	"Leisure Activities","skate","Skate","0","0"	},
        {	"Leisure Activities","picture-take-a","Take A Picture","0","0"	},
        {	"Leisure Activities","team","Team","0","0"	},
        {	"Leisure Activities","volunteer","Volunteer","0","0"	},
        {	"Numbers","23","23","0","0"	},
        {	"Numbers","25","25","0","0"	},
        {	"Numbers","34","34","0","0"	},
        {	"Numbers","35","35","0","0"	},
        {	"Numbers","40s","40","0","0"	},
        {	"Numbers","100","100","0","0"	},
        {	"Numbers","200","200","0","0"	},
        {	"Numbers","300","300","0","0"	},
        {	"Numbers","400","400","0","0"	},
        {	"Numbers","500","500","0","0"	},
        {	"Numbers","600","600","0","0"	},
        {	"Numbers","700","700","0","0"	},
        {	"Numbers","800","800","0","0"	},
        {	"Numbers","900","900","0","0"	},
        {	"Numbers","2000","2000","0","0"	},
        {	"Numbers","2397","2397","0","0"	},
        {	"Numbers","100c","1 Hundred","0","0"	},
        {	"Numbers","1000000","1 Million","0","0"	},
        {	"Numbers","1000b","1 Thousand","0","0"	},
        {	"Numbers","1000r","1 Thousand","0","0"	},
        {	"Places","africaa","Africa","0","0"	},
        {	"Places","africab","Africa","0","0"	},
        {	"Places","arizona","Arizona","0","0"	},
        {	"Places","atlanta","Atlanta","0","0"	},
        {	"Places","boston","Boston","0","0"	},
        {	"Places","boston2","Boston","0","0"	},
        {	"Places","chicago","Chicago","0","0"	},
        {	"Places","chinanew","China","0","0"	},
        {	"Places","country","Country","0","0"	},
        {	"Places","dallas","Dallas","0","0"	},
        {	"Places","dallasuncommon","Dallas","0","0"	},
        {	"Places","detroit","Detroit","0","0"	},
        {	"Places","earth","Earth","0","0"	},
        {	"Places","europe","Europe","0","0"	},
        {	"Places","german","German","0","0"	},
        {	"Places","ireland","Ireland","0","0"	},
        {	"Places","island","Island","0","0"	},
        {	"Places","nation","Nation","0","0"	},
        {	"Places","newyork","Newyork","0","0"	},
        {	"Places","ocean","Ocean","0","0"	},
        {	"Places","pittsburg","Pittsburg","0","0"	},
        {	"Places","river","River","0","0"	},
        {	"Places","russia","Russia","0","0"	},
        {	"Places","spain","Spain","0","0"	},
        {	"Places","texas","Texas","0","0"	},
        {	"Places","world","World","0","0"	},
        {	"Shapes","large","Large","0","0"	},
        {	"Shapes","small","Small","0","0"	},
        {	"Shapes","small-b","Small","0","0"	},
        {	"Shapes","small-c","Small","0","0"	},
        {	"Time","oclock-1","1 Oclock","0","0"	},
        {	"Time","oclock3","3 Oclock","0","0"	},
        {	"Time","week-3weeks","3 Weeks","0","0"	},
        {	"time","year-3years","3 Years","0","0"	},
        {	"Time","annually","Annually","0","0"	},
        {	"Time","annually2","Annually","0","0"	},
        {	"Time","christmas","Christmas","0","0"	},
        {	"Time","christmas2","Christmas","0","0"	},
        {	"Time","easter","Easter","0","0"	},
        {	"Time","laborday","Laborday","0","0"	},
        {	"Time","past","Past","0","0"	},
        {	"Time","postpone","Postpone","0","0"	},
        {	"Time","month-sixmonths","Six Months","0","0"	},
        {	"Time","thanksgiving","Thanksgiving","0","0"	},
        {	"Time","then","Then","0","0"	},
        {	"Time","time","Time","0","0"	}};;

        for(int i=0; i<gifs.length; i++){
            String cat=gifs[i][0].trim();
            String gif= gifs[i][1].trim();
            String title= gifs[i][2].trim();
            Sign newSign = new Sign(gif, title);
            db.getRef("categories").child(cat).child(gif).setValue(newSign);


        }

//        String[][] giff = new String[][]{{"100","100"},
//                {"1000000","1000000"},
//                {"1000b","1000b"},
//                {"1000r","1000r"},
//                {"100c","100c"},
//                {"200","200"},
//                {"2000","2000"},
//                {"23","23"},
//                {"2397","2397"},
//                {"25","25"},
//                {"300","300"},
//                {"33","34"},
//                {"35","35"},
//                {"400","400"},
//                {"40s","40s"},
//                {"500","500"},
//                {"600","600"},
//                {"700","700"},
//                {"800","800"},
//                {"900","900"},
//                {"aboutag","aboutag"},
//                {"about-approximately","about-approximately"},
//                {"aboveag","aboveag"},
//                {"aboveaglarge","aboveaglarge"},
//                {"abovemorethan","abovemorethan"},
//                {"accept","accept"},
//                {"accompany-along","accompany-along"},
//                {"accountantag","accountantag"},
//                {"acrossfromag","acrossfromag"},
//                {"actor","actor"},
//                {"addag","addag"},
//                {"addplusag","addplusag"},
//                {"addto","addto"},
//                {"africaa","africaa"},
//                {"africab","africab"},
//                {"against","against"},
//                {"ahead","ahead"},
//                {"air","air"},
//                {"all","all"},
//                {"all2","all2"},
//                {"all-lexicalized","all-lexicalized"},
//                {"all-lexicalized-b","all-lexicalized-b"},
//                {"allowag","allowag"},
//                {"alltogether","alltogether"},
//                {"almost","almost"},
//                {"alrightdouble","alrightdouble"},
//                {"alrightsingle","alrightsingle"},
//                {"alwaysanimation","always"},
//                {"am","am"},
//                {"american","american"},
//                {"americanindian","americanindian"},
//                {"an","an"},
//                {"and","and"},
//                {"animal","animal"},
//                {"annually","annually"},
//                {"annually2","annually2"},
//                {"another","another"},
//                {"answer","answer"},
//                {"any","any"},
//                {"anything","anything"},
//                {"apartment","apartment"},
//                {"approximately","approximately"},
//                {"area","area"},
//                {"arguea","arguea"},
//                {"argueb","argueb"},
//                {"arizona","arizona"},
//                {"around","around"},
//                {"arrive","arrive"},
//                {"artist","artist"},
//                {"as","as"},
//                {"assistant","assistant"},
//                {"at","at"},
//                {"atlanta","atlanta"},
//                {"away","away"},
//                {"awful","awful"},
//                {"awkward","awkward"},
//                {"babysiter","babysiter"},
//                {"babysitterb","babysitterb"},
//                {"bachelor","bachelor"},
//                {"back-backthere","back-backthere"},
//                {"back-body","back-body"},
//                {"back-lexicalized","back-lexicalized"},
//                {"bakeanimation","bake"},
//                {"balda","balda"},
//                {"baldb","baldb"},
//                {"baldc","baldc"},
//                {"ball","ball"},
//                {"banana","banana"},
//                {"bandage","bandage"},
//                {"bank","bank"},
//                {"baseball","baseball"},
//                {"basementanimation","basement"},
//                {"basketball","basketball"},
//                {"bat","bat"},
//                {"bat-flying","bat-flying"},
//                {"bathtubanimation","bathtub"},
//                {"bat-vampire","bat-vampire"},
//                {"be","be"},
//                {"bear","bear"},
//                {"bearda","bearda"},
//                {"beardb","beardb"},
//                {"becausea","becausea"},
//                {"becauseb","becauseb"},
//                {"becausec","becausec"},
//                {"become","become"},
//                {"bedmake","bedmake"},
//                {"bee","bee"},
//                {"begin","begin"},
//                {"belowbeneath","belowbeneath"},
//                {"belowbottom","belowbottom"},
//                {"belowlessthan","belowlessthan"},
//                {"bench","bench"},
//                {"best","best"},
//                {"better","better"},
//                {"betweena","betweena"},
//                {"betweenaverage","betweenaverage"},
//                {"betweeninbetween","betweeninbetween"},
//                {"bill2","bill2"},
//                {"birth","birth"},
//                {"blouse","blouse"},
//                {"board","board"},
//                {"bodyshift-oranimation","bodyshift-or"},
//                {"bookanimation","book"},
//                {"book-closebook","book-closebook"},
//                {"book-openbook","book-openbook"},
//                {"boss","boss"},
//                {"boston","boston"},
//                {"boston2","boston2"},
//                {"bother","bother"},
//                {"bottom","bottom"},
//                {"bra","bra"},
//                {"breadsideview","breadsideview"},
//                {"brother-step","brother-step"},
//                {"but","but"},
//                {"butter","butter"},
//                {"cafeteria","cafeteria"},
//                {"cake","cake"},
//                {"call-summon","call-summon"},
//                {"calm-down","calm-down"},
//                {"camera","camera"},
//                {"can-able","can-able"},
//                {"cancel","cancel"},
//                {"cant","cant"},
//                {"cantanimated","cantanimated"},
//                {"careful","careful"},
//                {"careless","careless"},
//                {"carpenter","carpenter"},
//                {"carry","carry"},
//                {"catanimation","cat"},
//                {"catbanimation","catb"},
//                {"chair","chair"},
//                {"character","character"},
//                {"chase","chase"},
//                {"chase2","chase2"},
//                {"chat-with-a","chat-with-a"},
//                {"chat-with-b","chat-with-b"},
//                {"cheap","cheap"},
//                {"cheat","cheat"},
//                {"check","check"},
//                {"chicago","chicago"},
//                {"child","child"},
//                {"children","children"},
//                {"childrentwohanded","childrentwohanded"},
//                {"chinanew","chinanew"},
//                {"chineseold","chineseold"},
//                {"chips","chips"},
//                {"chipshomesign","chipshomesign"},
//                {"christmas","christmas"},
//                {"christmas2","christmas2"},
//                {"class","class"},
//                {"classifier","classifier"},
//                {"classroom","classroom"},
//                {"clever","clever"},
//                {"climb","climb"},
//                {"closecaptioned","closecaptioned"},
//                {"closecaptioned2","closecaptioned2"},
//                {"clothesanimated","clothesanimated"},
//                {"cluster","cluster"},
//                {"coat","coat"},
//                {"coffee","coffee"},
//                {"collect","collect"},
//                {"committee","committee"},
//                {"computer","computer"},
//                {"computerkelsey","computerkelsey"},
//                {"conflict","conflict"},
//                {"connect","connect"},
//                {"connectto","connectto"},
//                {"contact","contact"},
//                {"cook","cook"},
//                {"corner","corner"},
//                {"couch","couch"},
//                {"couchanimation","couch"},
//                {"cough","cough"},
//                {"cough2","cough2"},
//                {"cough3","cough3"},
//                {"country","country"},
//                {"cowanimation","cow"},
//                {"crack","crack"},
//                {"crack2","crack2"},
//                {"crackegg","crackegg"},
//                {"crazy","crazy"},
//                {"crazy2","crazy2"},
//                {"cupboard","cupboard"},
//                {"dad-step","dad-step"},
//                {"dallas","dallas"},
//                {"dallasuncommon","dallasuncommon"},
//                {"dark","dark"},
//                {"daughter","daughter"},
//                {"daughterb","daughterb"},
//                {"dead-rigormortis","dead-rigormortis"},
//                {"deafanimation","deaf"},
//                {"decide","decide"},
//                {"decrease","decrease"},
//                {"delicious","delicious"},
//                {"demote","demote"},
//                {"deplete","deplete"},
//                {"deposit","deposit"},
//                {"depressed","depressed"},
//                {"destroy","destroy"},
//                {"deteriorate","deteriorate"},
//                {"deteriorate2","deteriorate2"},
//                {"detroit","detroit"},
//                {"diaper","diaper"},
//                {"dictionary","dictionary"},
//                {"did","did"},
//                {"die","die"},
//                {"different","different"},
//                {"differenta","differenta"},
//                {"different-very","different-very"},
//                {"dig","dig"},
//                {"dig2","dig2"},
//                {"dinosaur","dinosaur"},
//                {"discuss","discuss"},
//                {"disgusted","disgusted"},
//                {"dizzy","dizzy"},
//                {"doctor","doctor"},
//                {"dogaanimation","doga"},
//                {"dogbanimation","dogb"},
//                {"dog-d-o-ganimation","dog-d-o-g"},
//                {"doll","doll"},
//                {"donkey","donkey"},
//                {"dont","dont"},
//                {"dontcare","dontcare"},
//                {"dontmind","dontmind"},
//                {"dooranimation","door"},
//                {"down","down"},
//                {"dozen","dozen"},
//                {"drawer","drawer"},
//                {"dream","dream"},
//                {"dresseranimation","dresser"},
//                {"dribble","dribble"},
//                {"drill","drill"},
//                {"drink-up","drink-up"},
//                {"dripleak","dripleak"},
//                {"drop","drop"},
//                {"drunk","drunk"},
//                {"dryeranimation","dryer"},
//                {"duck","duck"},
//                {"during-along","during-along"},
//                {"duty","duty"},
//                {"each","each"},
//                {"eachversion2","eachversion2"},
//                {"eagle","eagle"},
//                {"earrings","earrings"},
//                {"earth","earth"},
//                {"earthquake","earthquake"},
//                {"easter","easter"},
//                {"elementary","elementary"},
//                {"elephant","elephant"},
//                {"elephantversion2","elephantversion2"},
//                {"emailanimation","email"},
//                {"emailb","emailb"},
//                {"emergency","emergency"},
//                {"emergencyvehicleanimation","emergencyvehicle"},
//                {"enjoy","enjoy"},
//                {"enter","enter"},
//                {"enthusiastic","enthusiastic"},
//                {"equalanimation","equal"},
//                {"establish","establish"},
//                {"europe","europe"},
//                {"every","every"},
//                {"everyversion2","everyversion2"},
//                {"exact","exact"},
//                {"excuse","excuse"},
//                {"excuselayoff","excuselayoff"},
//                {"exit","exit"},
//                {"exit-out","exit-out"},
//                {"explain","explain"},
//                {"fail","fail"},
//                {"failb","failb"},
//                {"failc","failc"},
//                {"faild","faild"},
//                {"fallbehind","fallbehind"},
//                {"fall-down","fall-down"},
//                {"fallinlove","fallinlove"},
//                {"false","false"},
//                {"fancy","fancy"},
//                {"farm","farm"},
//                {"farmer","farmer"},
//                {"farnotfar","farnotfar"},
//                {"father-step","father-step"},
//                {"fault","fault"},
//                {"feed","feed"},
//                {"feet","feet"},
//                {"figure","figure"},
//                {"find","find"},
//                {"fire","fire"},
//                {"fireman","fireman"},
//                {"firemanb","firemanb"},
//                {"first","first"},
//                {"first-b","first-b"},
//                {"first-c","first-c"},
//                {"first-place","first-place"},
//                {"fishanimation","fish"},
//                {"fishinganimation","fishing"},
//                {"follow","follow"},
//                {"for","for"},
//                {"force","force"},
//                {"for-for","for-for"},
//                {"forgeta","forgeta"},
//                {"forgetb","forgetb"},
//                        {"furniture","furniture"},
//                        {"garageanimation","garage"},
//                        {"german","german"},
//                        {"getanimation","get"},
//                        {"get-becomeanimation","get-become"},
//                        {"ghost","ghost"},
//                        {"girl-littlegirlanimation","girl-littlegirl"},
//                        {"give-givetoeverybody","give-givetoeverybody"},
//                        {"give-handtoeachone","give-handtoeachone"},
//                        {"give-himgivetome","give-himgivetome"},
//                        {"give-megivehim","give-megivehim"},
//                        {"give-megiveyou","give-megiveyou"},
//                        {"give-up","give-up"},
//                        {"give-yougiveme","give-yougiveme"},
//                        {"glasses","glasses"},
//                        {"glassesb","glassesb"},
//                        {"gomakeyourbed","gomakeyourbed"},
//                        {"grass","grass"},
//                        {"group","group"},
//                        {"hairdryer","hairdryer"},
//                        {"have-to","have-to"},
//                        {"hearingaid","hearingaid"},
//                        {"hearoverhear","hearoverhear"},
//                        {"here-d","here-d"},
//                        {"here-e","here-e"},
//                        {"hike","hike"},
//                        {"himself","himself"},
//                        {"hitanimation","hit"},
//                        {"hockey","hockey"},
//                        {"holiday","holiday"},
//                        {"hurt","hurt"},
//                        {"icecream","icecream"},
//                        {"idea","idea"},
//                        {"if-a","if-a"},
//                        {"if-b","if-b"},
//                        {"if-c","if-c"},
//                        {"important","important"},
//                        {"impossible","impossible"},
//                        {"incompetent","incompetent"},
//                        {"increase","increase"},
//                        {"infection","infection"},
//                        {"inlaw","inlaw"},
//                        {"inlawbrother","inlawbrother"},
//                        {"inlawbrotherb","inlawbrotherb"},
//                        {"inlawsister","inlawsister"},
//                        {"internet","internet"},
//                        {"internetb","internetb"},
//                        {"intersection","intersection"},
//                        {"ireland","ireland"},
//                        {"island","island"},
//                        {"kitchenaanimation","kitchena"},
//                        {"kitchenbanimation","kitchenb"},
//                        {"knife","knife"},
//                        {"knifecutwithknife","knifecutwithknife"},
//                        {"knifeversion1","knifeversion1"},
//                        {"know","know"},
//                        {"know-b","know-b"},
//                        {"know-c","know-c"},
//                        {"know-that","know-that"},
//                        {"laborday","laborday"},
//                        {"largeanimation","large"},
//                        {"laugh","laugh"},
//                        {"laydown","laydown"},
//                        {"left-ontheleftside","left-ontheleftside"},
//                        {"lesson","lesson"},
//                        {"lessonsideview","lessonsideview"},
//                        {"library","library"},
//                        {"light-brightanimation","light-bright"},
//                        {"light-generalanimation","light-general"},
//                        {"light-headlightsanimation","light-headlights"},
//                        {"light-lampanimation","light-lamp"},
//                        {"light-matchanimation","light-match"},
//                        {"light-overheadanimation","light-overhead"},
//                        {"listen","listen"},
//                        {"little-bit","little-bit"},
//                        {"lookat","lookat"},
//                        {"lookat-that","lookat-that"},
//                        {"loud","loud"},
//                        {"luck","luck"},
//                        {"luckgoodluck","luckgoodluck"},
//                        {"machine","machine"},
//                        {"magician","magician"},
//                        {"make","make"},
//                        {"manversiona","manversiona"},
//                        {"manversionb","manversionb"},
//                        {"manversionc","manversionc"},
//                        {"math","math"},
//                        {"meaning","meaning"},
//                        {"member","member"},
//                        {"memorial","memorial"},
//                        {"microwaveanimation","microwave"},
//                        {"month-sixmonthsanimation","month-sixmonths"},
//                        {"more-one-more","more-one-more"},
//                        {"mother-step","mother-step"},
//                        {"mountain","mountain"},
//                        {"mouth","mouth"},
//                        {"move","move"},
//                        {"movie","movie"},
//                        {"music","music"},
//                        {"myself","myself"},
//                        {"nation","nation"},
//                        {"neighbor","neighbor"},
//                        {"neighborb","neighborb"},
//                        {"never","never"},
//                        {"new","new"},
//                        {"newyork","newyork"},
//                        {"next","next"},
//                        {"niceclean","niceclean"},
//                        {"noanimation","no"},
//                        {"not","not"},
//                        {"notasl","notasl"},
//                        {"nothing","nothing"},
//                        {"ocean","ocean"},
//                        {"oclock-1animation","oclock-1"},
//                        {"oclock3animation","oclock3"},
//                        {"of","of"},
//                        {"offc","offc"},
//                        {"offd","offd"},
//                        {"offe","offe"},
//                        {"oh-i-see-b","oh-i-see-b"},
//                        {"on","on"},
//                        {"onc","onc"},
//                        {"once","once"},
//                        {"ond","ond"},
//                        {"open-up-a-newspaper","open-up-a-newspaper"},
//                        {"or","or"},
//                        {"ounce","ounce"},
//                        {"ovenanimation","oven"},
//                        {"owe","owe"},
//                        {"own","own"},
//                        {"page","page"},
//                        {"pants","pants"},
//                        {"pantsb","pantsb"},
//                        {"party","party"},
//                        {"pass","pass"},
//                        {"past","past"},
//                        {"peachversion1","peachversion1"},
//                        {"peachversion2","peachversion2"},
//                        {"peanutbutter","peanutbutter"},
//                        {"people","people"},
//                        {"petanimation","pet"},
//                        {"phone","phone"},
//                        {"phone-ttycall","phone-ttycall"},
//                        {"phone-voicecall","phone-voicecall"},
//                        {"picturea","picturea"},
//                        {"pictureb","pictureb"},
//                        {"picture-take-a","picture-take-a"},
//                        {"pie","pie"},
//                        {"pilgrim","pilgrim"},
//                        {"pittsburg","pittsburg"},
//                        {"plan","plan"},
//                        {"planprepare","planprepare"},
//                        {"plant","plant"},
//                        {"play","play"},
//                        {"pleasecloseup","pleasecloseup"},
//                        {"poetry","poetry"},
//                        {"police","police"},
//                        {"policeb","policeb"},
//                        {"postpone","postpone"},
//                        {"postponeversion1","postponeversion1"},
//                        {"president","president"},
//                        {"printer","printer"},
//                        {"program","program"},
//                        {"progress","progress"},
//                        {"pumkin","pumkin"},
//                        {"put","put"},
//                        {"put-away","put-away"},
//                        {"put-inslot","put-inslot"},
//                        {"put-pack","put-pack"},
//                        {"put-sortout","put-sortout"},
//                        {"put-up-with","put-up-with"},
//                        {"quote","quote"},
//                        {"race","race"},
//                        {"readanimation","read"},
//                        {"reason","reason"},
//                        {"rebel","rebel"},
//                        {"refridgeratoranimation","refridgerator"},
//                        {"remember","remember"},
//                        {"right-ontherightside","right-ontherightside"},
//                        {"river","river"},
//                        {"riverwiggle","riverwiggle"},
//                        {"rollerblade","rollerblade"},
//                        {"rude","rude"},
//                        {"run","run"},
//                        {"run2","run2"},
//                        {"russia","russia"},
//                        {"same-f","same-f"},
//                        {"same-g","same-g"},
//                        {"same-h","same-h"},
//                        {"say-what-did-he-say","say-what-did-he-say"},
//                        {"scarf","scarf"},
//                        {"scientist","scientist"},
//                        {"scientistb","scientistb"},
//                        {"scooter","scooter"},
//                        {"second-place","second-place"},
//                        {"secret","secret"},
//                        {"secretary","secretary"},
//                        {"secretarya","secretarya"},
//                        {"secretaryc","secretaryc"},
//                        {"see","see"},
//                        {"seize","seize"},
//                        {"selfanimated","selfanimated"},
//                        {"self-yourselfanimated","self-yourselfanimated"},
//                        {"separatedanimation","separated"},
//                        {"sew1","sew1"},
//                        {"shaveversionb","shaveversionb"},
//                        {"shirt","shirt"},
//                        {"shoes","shoes"},
//                        {"shortanimation","short"},
//                        {"showeranimation","shower"},
//                        {"showupappear","showupappear"},
//                        {"shutup","shutup"},
//                        {"sick-laidout","sick-laidout"},
//                        {"signlanguage","signlanguage"},
//                        {"since","since"},
//                        {"singer","singer"},
//                        {"singer2","singer2"},
//                        {"single-b","single-b"},
//                        {"single-c","single-c"},
//                        {"sinkanimation","sink"},
//                        {"sink-s-i-n-kanimation","sink-s-i-n-k"},
//                        {"sister-step","sister-step"},
//                        {"sit","sit"},
//                        {"skate","skate"},
//                        {"sleepy","sleepy"},
//                        {"small","small"},
//                        {"small-b","small-b"},
//                        {"small-c","small-c"},
//                        {"smell","smell"},
//                        {"so","so"},
//                        {"socks","socks"},
//                        {"some","some"},
//                        {"somethinganimation","something"},
//                        {"sometimesanimation","sometimes"},
//                        {"son","son"},
//                        {"sonb","sonb"},
//                        {"sophomore","sophomore"},
//                        {"sorry","sorry"},
//                        {"spain","spain"},
//                        {"speak","speak"},
//                        {"spellversion2","spellversion2"},
//                        {"spread","spread"},
//                        {"stand-getup","stand-getup"},
//                        {"stand-up","stand-up"},
//                        {"start","start"},
//                        {"stay","stay"},
//                        {"steal","steal"},
//                        {"step","step"},
//                        {"still","still"},
//                        {"stoveanimation","stove"},
//                        {"stripes","stripes"},
//                        {"struggle","struggle"},
//                        {"study","study"},
//                        {"suppose","suppose"},
//                        {"suppose2","suppose2"},
//                        {"swell","swell"},
//                        {"swing","swing"},
//                        {"tableanimation","table"},
//                        {"take","take"},
//                        {"takeaway","takeaway"},
//                        {"takecareof","takecareof"},
//                        {"take-it-easy","take-it-easy"},
//                        {"take-pill","take-pill"},
//                        {"take-up","take-up"},
//                        {"talk","talk"},
//                        {"talk-with","talk-with"},
//                        {"talk-withb","talk-withb"},
//                        {"tea","tea"},
//                        {"team","team"},
//                        {"tell","tell"},
//                        {"tell-him","tell-him"},
//                        {"tell-me","tell-me"},
//                        {"temple","temple"},
//                        {"texas","texas"},
//                        {"thanksgiving","thanksgiving"},
//                        {"then","then"},
//                        {"there-c","there-c"},
//                        {"there-d","there-d"},
//                        {"thing","thing"},
//                        {"third-place","third-place"},
//                        {"throw","throw"},
//                        {"timeanimation","time"},
//                        {"toothpasteanimation","toothpaste"},
//                        {"trade","trade"},
//                        {"tradeexchange","tradeexchange"},
//                        {"tree","tree"},
//                        {"true-b","true-b"},
//                        {"tty","tty"},
//                        {"turkey","turkey"},
//                        {"turn","turn"},
//                        {"underwear","underwear"},
//                        {"up","up"},
//                        {"up-till-now-b","up-till-now-b"},
//                        {"uptilnow","uptilnow"},
//                        {"utahlex","utahlex"},
//                        {"vegetableversion2","vegetableversion2"},
//                        {"videotape","videotape"},
//                        {"visit","visit"},
//                        {"volunteer","volunteer"},
//                        {"waitress","waitress"},
//                        {"wake-up","wake-up"},
//                        {"walk","walk"},
//                        {"walkto","walkto"},
//                        {"wall","wall"},
//                        {"watchb","watchb"},
//                        {"way","way"},
//                        {"wearout","wearout"},
//                        {"week-3weeksanimation","week-3weeks"},
//                        {"weld","weld"},
//                        {"whatkind","whatkind"},
//                        {"which","which"},
//                        {"windowanimation","window"},
//                        {"window-closewindowanimation","window-closewindow"},
//                        {"window-openwindowanimation","window-openwindow"},
//                        {"wine","wine"},
//                        {"without","without"},
//                        {"wonderful","wonderful"},
//                        {"world","world"},
//                        {"worse","worse"},
//                                {"year-3years","year-3years"},
//                                {"yellanimation","yell"},
//                                {"yesanimation","yes"},
//                                {"young","young"},
//                                {"you-somewhatsurprised","you-somewhatsurprised"},
//                                {"z2","z2"},
//                                {"zip","zip"}
//
//        };
//
//        for(int i=0; i<giffs.length; i++){
//            String cat=gifs[i][0].trim();
//            String gif= gifs[i][1].trim();
//            db.getRef("categories").child(cat).child(gif).setValue(true);
//            Sign newSign = new Sign(gif);
//            db.getRef("gifs").child(newSign.getUrl()).setValue(newSign);
//        }

        //user's email & password EditText
        emailText = (EditText) findViewById(R.id.userEmail);
        passwordText = (EditText) findViewById(R.id.userPassword);

        //create a new user button listener
        newUser = (Button) findViewById(R.id.createUser);
        newUser.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View view){
                email = emailText.getText().toString().trim();
                password = passwordText.getText().toString().trim();

                //if email or password are empty
                if ( TextUtils.isEmpty(email) || TextUtils.isEmpty(password) ) {
                    Toast.makeText(getApplicationContext(), "Email address or password is empty",
                            Toast.LENGTH_LONG).show();
                    return;
                }
                //if email does not contain @
                if( !email.contains("@") ){
                    Toast.makeText(getApplicationContext(), "Invalid email address",
                            Toast.LENGTH_LONG).show();
                    return;
                }
                //if password is less than 6 characters
                if(password.length() < 6){
                    Toast.makeText(getApplicationContext(), "Password must be longer than 6 characters",
                            Toast.LENGTH_LONG).show();
                    return;
                }
                //create new user
                auth.createUserWithEmailAndPassword(email, password)
                        .addOnCompleteListener(Login.this, new OnCompleteListener<AuthResult>() {
                            @Override
                            public void onComplete(@NonNull Task<AuthResult> task) {
                                Toast.makeText(getApplicationContext(), "New user created",
                                        Toast.LENGTH_LONG).show();
                                //if creating a new user was unsuccessful
                                if( !task.isSuccessful() ){
                                    Toast.makeText(getApplicationContext(), "Error occurred while creating new user",
                                            Toast.LENGTH_LONG).show();
                                }
                                //if creating a new user was successful
                                else{
                                    User newUser = new User(email);
                                    db.addNewUser(newUser);
                                    Intent intent = new Intent(Login.this, Homepage.class);
                                    startActivity(intent);
                                }
                            }
                        });
            }
        });


        //login button listener
        login = (Button) findViewById(R.id.loginButton);
        login.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View view){
                email = emailText.getText().toString();
                password = passwordText.getText().toString();
                //if email or password is empty
                if( TextUtils.isEmpty(email) || TextUtils.isEmpty(password) ){
                    Toast.makeText(getApplicationContext(), "Email or password is empty",
                            Toast.LENGTH_LONG).show();
                    return;
                }
                auth.signInWithEmailAndPassword(email, password)
                        .addOnCompleteListener(Login.this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        //if login was unsuccessful
                        if( !task.isSuccessful() ){
                            Toast.makeText(getApplicationContext(), "Error occurred during login.",
                                    Toast.LENGTH_LONG).show();
                        }
                        //if login was successful
                        else{
                            Intent intent = new Intent(Login.this, Homepage.class);
                            db.signIn();
                            startActivity(intent);
                        }
                    }
                });
            }
        });
    }
}
